name: net_player_next
description: netPlayer Flutter version
publish_to: 'none'
version: 3.1.4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_service: ^0.18.12
  crypto: ^3.0.3
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  hotkey_manager: ^0.1.8
  http: ^1.2.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  window_manager: ^0.3.8
  path_provider: ^2.1.2
  tray_manager: ^0.2.1
  google_fonts: ^6.2.1
  media_kit: ^1.1.10
  media_kit_libs_audio: ^1.0.4
  easy_debounce: ^2.0.3
  font_awesome_flutter: ^10.7.0
  flutter_popup: ^3.3.0
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.2
  flutter_rust_bridge: ^1.72.1
  smtc_windows: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"